### PR TITLE
Allow passing snowflake.connector.connect() params in DATABASES 'OPTIONS'

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by taylor-cedar** [comment]
Thanks @timgraham. This looks good. I will try it out this week.

**Comment by taylor-cedar** [comment]
Hey @timgraham. I tried this out. It seems to error with this
```
File "/Users/thakes/code/test_django/env/lib/python3.9/site-packages/django/db/backends/base/base.py", line 199, in connect
    conn_params = self.get_connection_params()
  File "/Users/thakes/code/test_django/django_snowflake/base.py", line 110, in get_connection_params
    raise ImproperlyConfigured(self.settings_is_missing % 'PASSWORD')
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is missing 'PASSWORD' for 'django_snowflake'.
```
When I commented out that error, it seemed to work.

**Comment by timgraham** [comment]
I added a commit to make PASSWORD optional if an authenticator is specified.

**Review by taylor-cedar — APPROVED** [review]
Looks and works great for me

**Pull request merged**
